version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build phase: no build commands for static site

artifacts:
  files:
    - '**/*'
  base-directory: .













